# Generated by Django 5.2.7 on 2026-03-05 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livro_ativo_alter_emprestimo_livro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='titulo_livro',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.livro'),
        ),
    ]
